# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code, run tests, and linting using node v20.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ðŸ§ª Tests & Linting

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release-v*'
  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20 (lts/iron) # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron
        cache: 'npm'
    - name: ðŸ”— Install Dependencies
      run: npm ci
    - name: ðŸ›  Build (Prod)
      run: npm run build
    - name: ðŸ“‘ Lint
      run: npm run lint
    - name: ðŸ§ª Unit Tests
      run: npm run test:unit
