# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ðŸ§ª Tests & Linting

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v20 (lts/iron) # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      uses: actions/setup-node@v3
      with:
        node-version: lts/iron
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  linting:
    needs: build
    steps:
    - run: npm run lint

  tests:
    needs: build
    steps:
    - run: npm run test:unit
